### ISSUE TITLE
python error in listdir

### ISSUE THREAD

**Issue by Bitti09** [FishStacks/4chan_downloader#1]
error message:

TypeError: listdir() takes exactly 1 argument (0 given)

**Comment by FishStacks** [comment]
there are many issues with this downloader, i haven't worked on it recently but i plan a full rewrite that should fix many of these obscure issues.
as for this issues what did the directory that you ran the program in contain (folders files etc)

**Comment by FishStacks** [comment]
due to lack of reply and my late reply (sorry) i'm closing this issue, it's probably related to the files you have in the current directory
